using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Foxy.PocoDictionary.SourceGenerator.Data;
using Foxy.PocoDictionary.SourceGenerator.Helpers;
using Microsoft.CodeAnalysis.Text;

namespace Foxy.PocoDictionary.SourceGenerator.SourceGenerator;

internal class OutputGenerator(SuccessfulCollectedData collectedData) : IDisposable
{
    private readonly SuccessfulCollectedData _collectedData = collectedData;
    private readonly SourceBuilder _builder = SourceBuilderPool.Instance.Get();

    public void Dispose()
    {
        SourceBuilderPool.Instance.Return(_builder);
    }

    public SourceText Execute()
    {
        _builder.AddAutoGeneratedComment();
        _builder.AppendLine();
        _builder.AddNullableEnable();
        _builder.AppendLine();
        GenerateNamespace();

        return SourceText.From(_builder.ToString(), Encoding.UTF8);
    }

    private void GenerateNamespace()
    {
        if (false)
        {
            GenerateNamespaceMembers();
        }
        else
        {
            var namespaceName = "Something";
            _builder.AppendLine($"namespace {namespaceName}");
            using (_builder.StartBlock())
            {
                GenerateNamespaceMembers();
            }
        }
    }

    private void GenerateNamespaceMembers()
    {
    }
}
